Update testRelease.yml

diff --git a/.github/workflows/testRelease.yml b/.github/workflows/testRelease.yml
--- a/.github/workflows/testRelease.yml
+++ b/.github/workflows/testRelease.yml
@@ -21,13 +21,13 @@ jobs:
         with:
           go-version: '1.20'
 
-      # Verify that the tag is correct
-      - name: Verify Tag
-        run: |
-          if [[ ! "${GITHUB_REF}" =~ ^refs/tags/v.*$ ]]; then
-            echo "Error: This is not a valid tag."
-            exit 1
-          fi
+      # # Verify that the tag is correct
+      # - name: Verify Tag
+      #   run: |
+      #     if [[ ! "${GITHUB_REF}" =~ ^refs/tags/v.*$ ]]; then
+      #       echo "Error: This is not a valid tag."
+      #       exit 1
+      #     fi
 
       # Install and Run GoReleaser
       - name: Install and Run GoReleaser
